version: '3.9'
networks:
  cme-network:
    name: "cme-network"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          ip_range: 10.5.0.0/24
          gateway: 10.5.0.1
          aux_addresses:
            kafka: 10.5.0.2
            zookeeper: 10.5.0.3

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    volumes:
      - postgres-data:/bitnami/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - "cme-network"

  redis:
    container_name: redis
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: your_password_here
    volumes:
      - redis-data:/bitnami/redis
    restart: unless-stopped
    networks:
      - "cme-network"

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: "zookeeper"
    ports:
      - 2181:2181
    volumes:
      - zookeeper-data:/var/lib/zookeeper
    networks:
      - "cme-network"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: "kafka"
    ports:
      - 9092:9092
      - 9093:9093
    networks:
      - "cme-network"
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_HOST://localhost:9093
      - KAFKA_RESTART_ATTEMPTS=10
      - KAFKA_RESTART_DELAY=5
      - ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL=0
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

volumes:
  postgres-data:
  redis-data:
  zookeeper-data:
  kafka-data:
    driver: local
